version: '3.3'
services:
  db:
    image: postgres:13-alpine
    restart: always
    ports:
      - '54325:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: books
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  website-backend:
    build:
      context: ./
      dockerfile: ./website/backend/Dockerfile
    volumes:
      - ./website/backend:/usr/src/app
    ports:
      - 5000:5000
    depends_on:
      - db
    command: ['./wait-for-it.sh', 'db:5432', '--', 'python', 'books_api.py']
  website-frontend:
    image: node:18
    user: node
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./website/frontend:/home/node/app
    expose:
      - 3000
    ports:
      - '3000:3000'
    command: 'npm start'

volumes:
  pgdata:
    driver: local
